# Generated by Django 4.0.5 on 2023-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('poster_image', models.URLField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('images', models.URLField(max_length=255)),
                ('stars', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
    ]
