# Generated by Django 4.0.5 on 2023-02-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='plot',
            field=models.CharField(max_length=1023, null=True),
        ),
    ]
